alias ls='ls --color=auto'
alias lls='tree -L 2'
alias llls='tree -L 3'
alias cdu='cd .. && ls'
alias rm='rm -i'
# alias rm='trash'
# alias rm='mv -t /tmp/'
alias vi="vim"
alias v="nvim"
alias sw='setxkbmap us; setxkbmap -option grp:switch,grp_led:scroll,grp:rctrl_switch us,es'
