site_name: Name Site
site_dir: build
markdown_extensions:
  - admonition #https://squidfunk.github.io/mkdocs-material/extensions/admonition/

plugins:
  - search
  #- pdf-export

theme:
  name: 'mkdocs' # 'mkdocs' 'material'
  highlightjs: false # true/false false para prueba sin internet

extra_css: [extra.css] # Active this (uncomment) if you have external css in docs/extra.css

nav:
  #  - Home: index.md

