site_name: Name Site
site_dir: build
markdown_extensions:
  - admonition #https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - attr_list

# use_directory_urls: false
plugins:
  - search
#  - pdf-export:
#      combined: true

lang: es

theme:
  name: 'mkdocs' # 'mkdocs' 'material'
  highlightjs: false # true/false false para prueba sin internet
  hljs_languages:
    - javascript
    - python
    - lua
    - c
    - c++
    - bash


extra_css: [extra.css] # Active this (uncomment) if you have external css in docs/extra.css

nav:
  #  - Home: index.md

