# Manual:
# https://just.systems/man/en/
# https://github.com/casey/just/tree/master/examples
# https://just.systems/man/en/functions.html?highlight=without#functions
# juts -l # Show rules commented

BUILD_DIR := "build"
SRC := "./letter-example.tex"
BASE_NAME := without_extension(SRC)
COMPILER := "lualatex"
VIEWER := "zathura"

# VIEWER := "pdfpc"
# VIEWER := "evince"

# Make a pdf from SRC
build:
    mkdir -p {{ BUILD_DIR }}
    {{ COMPILER }} -output-directory={{ BUILD_DIR }} -shell-escape {{ SRC }}

# View pdf in VIEWER
view:
    {{ VIEWER }} {{ BUILD_DIR }}/{{ BASE_NAME }}.pdf

clean:
    rm -f {{ BUILD_DIR }}/*

# Add BUILD_DIR into .gitignore file
gitignore:
    echo "build/" >> .gitignore

compress:
    tar czvf {{ BASE_NAME }}.tar.gz ./img ./src ./README.md {{ BASE_NAME }}.tex ./justfile
